# Generated by Django 4.1.2 on 2022-11-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_image_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='userimage')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
