# Generated by Django 4.1.2 on 2023-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_image_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='propertytype',
            field=models.TextField(default=None),
        ),
    ]
