# Generated by Django 4.1.2 on 2023-04-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_image_descp_alter_image_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
