# Generated by Django 4.2 on 2023-05-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_image_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='phone',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
