# Generated by Django 4.2 on 2023-05-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_image_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
