# Generated by Django 4.2 on 2023-05-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_image_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='phone',
            field=models.IntegerField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='propertytype',
            field=models.CharField(choices=[('Room', 'Rooms'), ('Flat', 'Flats'), ('House', 'Houses'), ('Other', 'Others')], default='Other', max_length=20),
        ),
    ]
