# Generated by Django 4.2 on 2023-06-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_image_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('imgfield', models.ImageField(default=None, upload_to='images/')),
                ('price', models.CharField(default=None, max_length=5)),
                ('payingmodel', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], default='Monthly', max_length=20)),
                ('descp', models.CharField(default=None, max_length=50)),
                ('attachedbathroom', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('wifiavailable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=5)),
                ('acfan', models.CharField(choices=[('AC', 'AC'), ('Fan', 'Fan')], default='Fan', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
