# Generated by Django 4.2 on 2023-06-05 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_rooms_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=10)),
                ('imgfield', models.ImageField(default=None, upload_to='images/')),
                ('price', models.CharField(default=None, max_length=5)),
                ('payingmodel', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi-Annually', 'Semi-Annually'), ('Annually', 'Annually')], default='Monthly', max_length=20)),
                ('descp', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='address',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='descp',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='imgfield',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='payingmodel',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='price',
        ),
        migrations.AddField(
            model_name='rooms',
            name='property',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='home.property'),
        ),
    ]
