# Generated by Django 4.2 on 2023-08-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_login_id_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientid',
            new_name='client',
        ),
    ]
