# Generated by Django 4.1.2 on 2022-11-20 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Signup',
        ),
    ]
