# Generated by Django 4.1.2 on 2022-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
