# Generated by Django 4.1.2 on 2023-01-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_delete_signup_alter_image_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='Gallery',
        ),
    ]
