# Generated by Django 4.1.2 on 2023-01-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_image_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
