# Generated by Django 4.1.2 on 2023-03-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_image_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='phone',
            field=models.TextField(default=None, max_length=10),
        ),
    ]
