# Generated by Django 4.1.2 on 2023-03-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_image_desc_image_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='desc',
            field=models.TextField(default=None, max_length=200),
        ),
    ]
