# Generated by Django 4.1.2 on 2023-03-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_image_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
    ]
