# Generated by Django 4.1.2 on 2023-04-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_image_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='descp',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
