# Generated by Django 4.1.2 on 2023-04-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_image_descp_image_propertytype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='home_image',
        ),
    ]
