# Generated by Django 4.1.2 on 2023-04-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_image_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
    ]
