# Generated by Django 4.2 on 2023-05-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_image_phone_alter_image_propertytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
