# Generated by Django 4.2 on 2023-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_image_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
