# Generated by Django 4.2 on 2023-05-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_image_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
