# Generated by Django 4.2 on 2023-05-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_roomsdetails_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsdetails',
            name='price',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
