# Generated by Django 4.2 on 2023-05-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_roomsdetails_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomsdetails',
            old_name='img',
            new_name='imgfield',
        ),
    ]
